"""Catálogos cerrados del contrato `residenciafiscal-case/3`."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, StringConstraints

Identifier = Annotated[
    str,
    StringConstraints(pattern=r"^[a-z0-9]+(?:-[a-z0-9]+)*$", min_length=1),
]
Sha256 = Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")]
NonEmptyText = Annotated[str, StringConstraints(min_length=1)]


class JurisprudenceCaseModel(BaseModel):
    """Configuración común de los modelos jurídicos v3."""

    model_config = ConfigDict(extra="forbid", frozen=True)


class TechnicalReviewState(StrEnum):
    GENERATED = "GENERATED"
    VALIDATED = "VALIDATED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECTED = "REJECTED"


class LegalReviewState(StrEnum):
    UNREVIEWED = "UNREVIEWED"
    AGENT_REVIEWED = "AGENT_REVIEWED"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    REJECTED = "REJECTED"


class AnchorFidelity(StrEnum):
    EXACT = "EXACT"
    EXACT_WITH_ELLIPSIS = "EXACT_WITH_ELLIPSIS"


class AnchorPurpose(StrEnum):
    FACT = "FACT"
    EVIDENCE = "EVIDENCE"
    HOLDING = "HOLDING"
    REASONING = "REASONING"
    LEGAL_RULE = "LEGAL_RULE"
    BURDEN_OF_PROOF = "BURDEN_OF_PROOF"
    TREATY = "TREATY"


class IssueType(StrEnum):
    TAX_RESIDENCE = "TAX_RESIDENCE"
    PHYSICAL_PRESENCE_183_DAYS = "PHYSICAL_PRESENCE_183_DAYS"
    SPORADIC_ABSENCES = "SPORADIC_ABSENCES"
    ECONOMIC_INTERESTS = "ECONOMIC_INTERESTS"
    VITAL_INTERESTS = "VITAL_INTERESTS"
    FAMILY_PRESUMPTION = "FAMILY_PRESUMPTION"
    HOUSING_AND_EFFECTIVE_USE = "HOUSING_AND_EFFECTIVE_USE"
    FOREIGN_TAX_DOCUMENTATION = "FOREIGN_TAX_DOCUMENTATION"
    TREATY_TIEBREAKER = "TREATY_TIEBREAKER"
    BURDEN_OF_PROOF = "BURDEN_OF_PROOF"
    TAX_ASSESSMENT = "TAX_ASSESSMENT"
    UNEXPLAINED_CAPITAL_GAIN = "UNEXPLAINED_CAPITAL_GAIN"
    PENALTY = "PENALTY"
    OTHER = "OTHER"


class CriterionId(StrEnum):
    DAYS_183 = "CRIT_183_DIAS"
    SPORADIC_ABSENCES = "CRIT_AUSENCIAS_ESPORADICAS"
    ECONOMIC_INTERESTS = "CRIT_CENTRO_INTERESES_ECONOMICOS"
    VITAL_INTERESTS = "CRIT_CENTRO_INTERESES_VITALES"
    FAMILY_PRESUMPTION = "CRIT_PRESUNCION_FAMILIA"
    TREATY_TIEBREAKER = "CRIT_CDI_TIEBREAKER"
    OTHER = "CRIT_OTRO"


class SubjectRole(StrEnum):
    TAXPAYER = "TAXPAYER"
    SPOUSE = "SPOUSE"
    DEPENDENT = "DEPENDENT"
    ADMINISTRATION = "ADMINISTRATION"
    ENTITY = "ENTITY"
    THIRD_PARTY = "THIRD_PARTY"
    OTHER = "OTHER"


class FactCategory(StrEnum):
    PRESENCE = "PRESENCE"
    TRAVEL = "TRAVEL"
    HOUSING = "HOUSING"
    FAMILY = "FAMILY"
    EMPLOYMENT = "EMPLOYMENT"
    ECONOMIC_ACTIVITY = "ECONOMIC_ACTIVITY"
    INCOME = "INCOME"
    ASSETS = "ASSETS"
    BANKING = "BANKING"
    CONSUMPTION = "CONSUMPTION"
    HEALTH = "HEALTH"
    ADMINISTRATIVE_LINK = "ADMINISTRATIVE_LINK"
    FOREIGN_TAX = "FOREIGN_TAX"
    PROCEDURAL = "PROCEDURAL"
    OTHER = "OTHER"


class AssertionParty(StrEnum):
    AEAT = "AEAT"
    TAXPAYER = "TAXPAYER"
    COURT = "COURT"
    UNDISPUTED = "UNDISPUTED"
    OTHER = "OTHER"


class ProceduralFactStatus(StrEnum):
    ALLEGED = "ALLEGED"
    DISPUTED = "DISPUTED"
    PROVEN = "PROVEN"
    NOT_PROVEN = "NOT_PROVEN"
    UNDISPUTED = "UNDISPUTED"
    UNKNOWN = "UNKNOWN"


class EvidenceParty(StrEnum):
    AEAT = "AEAT"
    TAXPAYER = "TAXPAYER"
    COURT_OBTAINED = "COURT_OBTAINED"
    OTHER = "OTHER"


class EvidenceAssessment(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    PARTIAL = "PARTIAL"
    UNRESOLVED = "UNRESOLVED"
    NOT_ASSESSED = "NOT_ASSESSED"


class EvidenceRole(StrEnum):
    DECISIVE = "DECISIVE"
    CORROBORATIVE = "CORROBORATIVE"
    CONTRADICTORY = "CONTRADICTORY"
    CONTEXTUAL = "CONTEXTUAL"
    UNKNOWN = "UNKNOWN"


class LegalRuleType(StrEnum):
    STATUTE = "STATUTE"
    TREATY = "TREATY"
    CASE_LAW = "CASE_LAW"
    ADMINISTRATIVE_GUIDANCE = "ADMINISTRATIVE_GUIDANCE"
    OTHER = "OTHER"


class IssueOutcome(StrEnum):
    GANA_AEAT = "GANA_AEAT"
    GANA_CONTRIBUYENTE = "GANA_CONTRIBUYENTE"
    PARCIAL = "PARCIAL"
    RETROACCION = "RETROACCION"
    INADMISION = "INADMISION"
    NO_RESUELTO = "NO_RESUELTO"
    OTROS = "OTROS"


class SpanishResidenceStatus(StrEnum):
    RESIDENT_IN_SPAIN = "RESIDENT_IN_SPAIN"
    NON_RESIDENT_IN_SPAIN = "NON_RESIDENT_IN_SPAIN"
    PARTIAL_YEAR_IN_SPAIN = "PARTIAL_YEAR_IN_SPAIN"
    NOT_DECIDED = "NOT_DECIDED"


class ProofParty(StrEnum):
    AEAT = "AEAT"
    TAXPAYER = "TAXPAYER"
    BOTH = "BOTH"
    COURT = "COURT"
    OTHER = "OTHER"


class TieBreakerCriterion(StrEnum):
    PERMANENT_HOME = "VIVIENDA_PERMANENTE"
    VITAL_INTERESTS = "CENTRO_INTERESES_VITALES"
    HABITUAL_ABODE = "MORADA_HABITUAL"
    NATIONALITY = "NACIONALIDAD"
    MUTUAL_AGREEMENT = "ACUERDO_MUTUO"
    NOT_STATED = "NO_CONSTA"
    NOT_APPLICABLE = "NO_APLICA"


class EvidenceCategory(StrEnum):
    PHYSICAL_PRESENCE = "PRESENCIA_FISICA_Y_DESPLAZAMIENTOS"
    HOUSING = "VIVIENDA_Y_USO_EFECTIVO"
    HOUSEHOLD_CONSUMPTION = "SUMINISTROS_Y_CONSUMOS_DOMESTICOS"
    FINANCIAL_CONSUMPTION = "CONSUMOS_FINANCIEROS"
    FAMILY = "FAMILIA_Y_ENTORNO_PERSONAL"
    HEALTH = "SALUD_Y_SERVICIOS_PERSONALES"
    ECONOMIC_ACTIVITY = "ACTIVIDAD_ECONOMICA_Y_GESTION"
    FOREIGN_TAX_DOCUMENTATION = "DOCUMENTACION_FISCAL_EXTRANJERA"
    SPANISH_ADMINISTRATIVE_LINKS = "VINCULOS_ADMINISTRATIVOS_EN_ESPANA"
    DIGITAL_TRACES = "TRAZAS_DIGITALES"
    TESTIMONY_AND_EXPERT = "TESTIFICAL_Y_PERICIAL"
    OTHER = "OTROS"
