-- Guardarraíles operativos para el purgado del chat.
--
-- El patrón sigue al servicio GDPR de Presupuestor: el job queda desactivado
-- por configuración, empieza en dry-run y no borra un lote anormalmente
-- grande sin intervención. La retención legal sigue siendo una decisión
-- externa: la función solo recibe el cutoff ya aprobado.

CREATE TABLE private.chat_retention_purge_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_at timestamptz NOT NULL DEFAULT now(),
    cutoff timestamptz NOT NULL,
    dry_run boolean NOT NULL,
    batch_limit integer NOT NULL CHECK (batch_limit > 0),
    status text NOT NULL CHECK (status IN ('dry_run', 'completed', 'batch_overflow')),
    messages_candidates bigint NOT NULL DEFAULT 0 CHECK (messages_candidates >= 0),
    requests_candidates bigint NOT NULL DEFAULT 0 CHECK (requests_candidates >= 0),
    conversations_candidates bigint NOT NULL DEFAULT 0 CHECK (conversations_candidates >= 0),
    messages_deleted bigint NOT NULL DEFAULT 0 CHECK (messages_deleted >= 0),
    requests_deleted bigint NOT NULL DEFAULT 0 CHECK (requests_deleted >= 0),
    conversations_deleted bigint NOT NULL DEFAULT 0 CHECK (conversations_deleted >= 0),
    executor text NOT NULL DEFAULT 'scheduler'
);

CREATE INDEX chat_retention_purge_audit_run_at_idx
    ON private.chat_retention_purge_audit (run_at DESC);

ALTER TABLE private.chat_retention_purge_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE private.chat_retention_purge_audit
    FROM PUBLIC, anon, authenticated, service_role;

DROP FUNCTION IF EXISTS private.purge_expired_chat_data(timestamptz);

CREATE OR REPLACE FUNCTION private.purge_expired_chat_data(
    p_cutoff timestamptz,
    p_dry_run boolean DEFAULT true,
    p_batch_limit integer DEFAULT 500
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, private
AS $$
DECLARE
    v_messages_candidates bigint := 0;
    v_requests_candidates bigint := 0;
    v_conversations_candidates bigint := 0;
    v_messages_deleted bigint := 0;
    v_requests_deleted bigint := 0;
    v_conversations_deleted bigint := 0;
    v_status text;
BEGIN
    IF p_cutoff IS NULL OR p_cutoff >= clock_timestamp() THEN
        RAISE EXCEPTION 'invalid chat retention cutoff';
    END IF;

    IF p_dry_run IS NULL THEN
        RAISE EXCEPTION 'invalid chat retention dry-run flag';
    END IF;

    IF p_batch_limit IS NULL OR p_batch_limit NOT BETWEEN 1 AND 100000 THEN
        RAISE EXCEPTION 'invalid chat retention batch limit';
    END IF;

    SELECT count(*)
      INTO v_requests_candidates
      FROM private.chat_requests
     WHERE created_at < p_cutoff;

    SELECT count(*)
      INTO v_messages_candidates
      FROM private.chat_messages AS messages
      JOIN private.chat_requests AS requests
        ON requests.request_id = messages.request_id
     WHERE requests.created_at < p_cutoff;

    SELECT count(*)
      INTO v_conversations_candidates
      FROM private.chat_conversations AS conversations
     WHERE conversations.updated_at < p_cutoff
       AND NOT EXISTS (
           SELECT 1
             FROM private.chat_requests AS requests
            WHERE requests.conversation_id = conversations.conversation_id
       );

    IF greatest(
        v_messages_candidates,
        v_requests_candidates,
        v_conversations_candidates
    ) > p_batch_limit THEN
        v_status := 'batch_overflow';

        INSERT INTO private.chat_retention_purge_audit (
            cutoff,
            dry_run,
            batch_limit,
            status,
            messages_candidates,
            requests_candidates,
            conversations_candidates
        )
        VALUES (
            p_cutoff,
            p_dry_run,
            p_batch_limit,
            v_status,
            v_messages_candidates,
            v_requests_candidates,
            v_conversations_candidates
        );

        RETURN jsonb_build_object(
            'status', v_status,
            'cutoff', p_cutoff,
            'dry_run', p_dry_run,
            'batch_limit', p_batch_limit,
            'messages_candidates', v_messages_candidates,
            'requests_candidates', v_requests_candidates,
            'conversations_candidates', v_conversations_candidates,
            'messages_deleted', 0,
            'requests_deleted', 0,
            'conversations_deleted', 0
        );
    END IF;

    IF p_dry_run THEN
        v_status := 'dry_run';

        INSERT INTO private.chat_retention_purge_audit (
            cutoff,
            dry_run,
            batch_limit,
            status,
            messages_candidates,
            requests_candidates,
            conversations_candidates
        )
        VALUES (
            p_cutoff,
            true,
            p_batch_limit,
            v_status,
            v_messages_candidates,
            v_requests_candidates,
            v_conversations_candidates
        );

        RETURN jsonb_build_object(
            'status', v_status,
            'cutoff', p_cutoff,
            'dry_run', true,
            'batch_limit', p_batch_limit,
            'messages_candidates', v_messages_candidates,
            'requests_candidates', v_requests_candidates,
            'conversations_candidates', v_conversations_candidates,
            'messages_deleted', 0,
            'requests_deleted', 0,
            'conversations_deleted', 0
        );
    END IF;

    DELETE FROM private.chat_messages AS messages
    USING private.chat_requests AS requests
     WHERE messages.request_id = requests.request_id
       AND requests.created_at < p_cutoff;
    GET DIAGNOSTICS v_messages_deleted = ROW_COUNT;

    DELETE FROM private.chat_requests
     WHERE created_at < p_cutoff;
    GET DIAGNOSTICS v_requests_deleted = ROW_COUNT;

    DELETE FROM private.chat_conversations AS conversations
     WHERE conversations.updated_at < p_cutoff
       AND NOT EXISTS (
           SELECT 1
             FROM private.chat_requests AS requests
            WHERE requests.conversation_id = conversations.conversation_id
       );
    GET DIAGNOSTICS v_conversations_deleted = ROW_COUNT;

    v_status := 'completed';

    INSERT INTO private.chat_retention_purge_audit (
        cutoff,
        dry_run,
        batch_limit,
        status,
        messages_candidates,
        requests_candidates,
        conversations_candidates,
        messages_deleted,
        requests_deleted,
        conversations_deleted
    )
    VALUES (
        p_cutoff,
        false,
        p_batch_limit,
        v_status,
        v_messages_candidates,
        v_requests_candidates,
        v_conversations_candidates,
        v_messages_deleted,
        v_requests_deleted,
        v_conversations_deleted
    );

    RETURN jsonb_build_object(
        'status', v_status,
        'cutoff', p_cutoff,
        'dry_run', false,
        'batch_limit', p_batch_limit,
        'messages_candidates', v_messages_candidates,
        'requests_candidates', v_requests_candidates,
        'conversations_candidates', v_conversations_candidates,
        'messages_deleted', v_messages_deleted,
        'requests_deleted', v_requests_deleted,
        'conversations_deleted', v_conversations_deleted
    );
END;
$$;

REVOKE ALL ON FUNCTION private.purge_expired_chat_data(timestamptz, boolean, integer)
    FROM PUBLIC, anon, authenticated, service_role;

COMMENT ON TABLE private.chat_retention_purge_audit IS
    'Auditoría backend-only de dry-runs, lotes rechazados y purgados del chat.';
COMMENT ON FUNCTION private.purge_expired_chat_data(timestamptz, boolean, integer) IS
    'Purgado con dry-run, límite por lote y auditoría; el cutoff lo decide la política aprobada.';
